### PR TITLE
Fix #1269 add chapter indicator to scrollbar

### LINKED ISSUE #1269: add chapter indicator to scroll view
We already have some simple functionality for this but there is a lot of room for improvement. We could use something like this https://github.com/danoz73/RecyclerViewFastScroller or this https://github.com/AnderWeb/discreteSeekBar

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fixes #1269 add chapter indicator to scrollbar

Changes in this pull request:
- Added SeekBarHint library to do the popup chapter numbers. 
  - Update to build in Android Studio version 2+
  - Tweaked size and placement of popup hint text.  
  - Modified to work with VerticalScrollBar.
- Added library to software licenses.
- Added fine adjustment support for when number of cards are few and large.
- Disabled graduations on scrollbar.

@neutrinog - note that this is using a different library than first attempt (PR 1534).

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - hold on - it looks like the method it uses to calculate position does not work on all screen sizes.  Needs more work.

**Comment by PhotoNomad0** [comment]
Looks like it is working for all screen sizes now, but positioning is off for KitKat.

**Comment by PhotoNomad0** [comment]
@neutrinog - sorry been out of town, but I have Kitkat support working now (tested multiple screen sizes).  Ready for review.

**Comment by PhotoNomad0** [comment]
@neutrinog - After merging with develop branch I cannot build for kitkat or Jellybean - get error that more than 64K methods in dex file.  In the develop branch I don’t see that.

**Comment by neutrinog** [comment]
I consolidated a bunch of code and removed large unneeded libraries. If your merged re-introduced those huge libraries then it will cause dex issues again. Try a rebase rather than a merge. e.g. rebase your branch onto develop. see https://git-scm.com/docs/git-rebase

**Comment by PhotoNomad0** [comment]
@neutrinog - OK removed a dependent library and have it building again for all platforms.

**Comment by PhotoNomad0** [comment]
@neutrinog - hold off on this one.  The text search changes will mean significant rework on this item.

**Comment by PhotoNomad0** [comment]
@neutrinog - this is now updated to handle changes in number of cards due to text search.

**Comment by PhotoNomad0** [comment]
@neutrinog - found bug with scroll position after search text changed.  Working on that now.

**Comment by PhotoNomad0** [comment]
@neutrinog - ok the seekbar updates now seem to accommodate the item count changes.

**Comment by PhotoNomad0** [comment]
@neutrinog - I dug through the 11,000 line travis log file and found the build failure.  the seekbarhint library had an empty text class that travis was choking on.  Removing the text class fixed the build.

**Comment by neutrinog** [comment]
@PhotoNomad0 The app crashes when in portrait mode.

**Comment by PhotoNomad0** [comment]
@neutrinog - sorry - it's a good reminder to me to retest thoroughly after making merge fixes.  It should work on rotation now.

**Pull request merged**
