### PR TITLE
Fix #1197 add footnote support

### LINKED ISSUE #1197: add back footnote support
Translators need to be able to add footnotes to their translation.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1197 add footnote support

@neutrinog - Here is a first pass at footnote support.  Has the basic functionality of insertion, editing and deleting.  Clicking on footnotes works when not in edit mode, but not in edit mode.  But that also is the current behavior for verse markers. Let me know what improvements I need to make here.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1237)

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 Could you pull in the latest from the develop branch? I just finished merging in a few pull requests and this one is coming up with conflicts.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK looks like there were conflicts in the string.xml file.  Not a big surprise.

**Comment by neutrinog** [comment]
@PhotoNomad0 finally getting back into android :)
Looks good I did have a question for @jag3773. See the screenshot below

screenshot_2016-02-09-18-22-27

Here you can see two examples of a footnote (icon vs yellow highlight). My question is which one do you want to use when creating a footnote? Occasionally I'll see both of these in the source text but it is primarily the one on the left. The main difference is one has a title and the other doesn't (thus the icon). Should we support both? Should we only allow them to create one type?

I see benefit to only support a title-*less* icon approach because it will prevent people from adding obnoxiously long titles that clutter the text.

**Comment by jag3773** [comment]
I don't think we need to support titles for footnotes.

**Comment by neutrinog** [comment]
great. @PhotoNomad0 I already tweaked the code for the titles a bit so I'll make this small change and merge this.

**Comment by PhotoNomad0** [comment]
@neutrinog - I like the looks of it better without the footnote titles.

**Pull request merged**
