### PR TITLE
Fix #1535 reject upload when there are pending changes on the server

### LINKED ISSUE #1535: Reject upload when there are pending changes on the server
See requirements at https://github.com/unfoldingWord-dev/ts-requirements/issues/145

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1535 reject upload when there are pending changes on the server

Changes in this pull request:

changes to detect push rejection, notifies HomeActivity that target has changed,  HomeActivity detects that change and prompts user to initiate merge.

@neutrinog - please take a look to see if you like this approach.

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 we need to display the merge conflict dialog like we did in the publish fragment. It needs to stay open when the user rotates the device as well.

e.g. keep their changes, keep the server changes, review, cancel.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK not clear here.  Do you want to move that merge conflict dialog into the import from door 43 dialog?  It wasn't in there.

**Comment by neutrinog** [comment]
Yes. It was missing there in the first place. But we can just move it from the publish fragment. See the requirements here https://github.com/unfoldingWord-dev/ts-requirements/issues/145.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK, that makes sense.

**Comment by neutrinog** [comment]
when I click on review differences after a merge conflict occurs it does not perform the merge at all.

**Comment by neutrinog** [comment]
still same issues except now when it takes me into the review mode and I hit the back button the app closes instead of taking me back to the home screen..

**Comment by PhotoNomad0** [comment]
@neutrinog - Made fixes to dialog rotation in ImportFromDoor43Dialog ImportDialog RestoreFromDoor43Dialog HomeActivity PublishFragment.

**Comment by PhotoNomad0** [comment]
@neutrinog - hold off on this, still doing testing - see a quirk.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK, hoping I've resolved all the rotation issues here.

**Comment by neutrinog** [comment]
@PhotoNomad0 can you update this pull request so it has the latest code from develop?

**Comment by PhotoNomad0** [comment]
@neutrinog - OK merged with develop.

**Comment by neutrinog** [comment]
merged in #1579

**Pull request closed without merging**
