### PR TITLE
Fix QA fail #1290 add interface for handling merge conflicts

### LINKED ISSUE #1255: add interface for handling merge conflicts
When importing we usually have two repositories available. We should first try to do a local git merge from one repository into the other. If conflicts arise then we should roll the changes back and ask the user which chapters/frames they want to import/overwrite. Possibly we could just ask this for the items that have conflicts.

This will solve issues with users' content getting overwritten during an import.

### LINKED ISSUE #1290: Create ui for handling merge conflicts
Please see #1255 for details on what the ui should look like. 

Users should not be allowed to move verse markers or directly edit the text in a chunk that has a merge conflict until they choose one of the following:
- keep green text
- keep red text
- keep both (for manually editing)

Until they choose one of the above if they tap on the chunk card they should be presented with a dialog explaining their options with appropriate confirmations/previews when making a selection.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1290 QA fail add interface for handling merge conflicts

Changes in this pull request:
- Fix for nested merge conflicts.
- Fix for setting font sizes on merge conflicts to address inconsistent sizing.

@neutrinog - ready to send to QA for review.  These changes got lost in merge with resource containers.

### CODE REVIEW

**Comment by neutrinog** [comment]
See line 465 in the ReviewModeAdapter. This ended up being an infinite loop in my test. I commented out the while statement (that was causing the infinite loop).

In my test I created 4 Genesis projects each with a different language. Then I edited the same chunk in all of them differently.
Then I merged two each together so I was left with two projects each having a merge conflict.
Finally I merged the two remaining projects together.

I noticed two things in doing this:

1. the infinite loop mentioned above that I temporarily disabled.
2. the rendering of the conflict is very odd (screen shot below)
3. if I choose one of the items to keep it remains rendered as a conflict instead of displaying my choice as a normal card.

A sample translation is at https://git.door43.org/joel/aa_exo_text_reg

screenshot_2016-11-01-17-07-35

**Comment by neutrinog** [comment]
I did some experimenting with regex and narrowed down to two expressions that will need to be used in tandem. The first expression will cover most of the usual cases and the second expression will cover a corner case.

run this first:

```
(?:<<<<<<<\s+HEAD\s)([^<>]*)=======([^<>]*)(?:>>>>>>>\s+refs\/heads\/new)
```

then run this:
```
(?:<<<<<<<\s+HEAD\s)([^<>]*)(=======)?([^<>]*)(?:>>>>>>>\s+refs\/heads\/new)
```

These will handle nested conflicts by starting at the most inner conflict and working out.

**Comment by PhotoNomad0** [comment]
@neutrinog - thanks will take a look at this.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK converted this to be a task.  Added a new test case and updated the unit tests to verify against the merge conflict task that returns an array of conflict options.  Also fixed a bug that can happen when cards get recycled.

**Comment by neutrinog** [comment]
much better!
I tried one more thing to test the merge conflicts.
Using the same sample project mentioned above, I added some text before and after the merge conflicts.

I'm not exactly sure how it's supposed to render text that is not part of the merge conflict, but it is not consistent.  

screenshot_2016-11-03-15-18-03

screenshot_2016-11-03-15-18-30

screenshot_2016-11-03-15-18-35

**Comment by neutrinog** [comment]
This is the actual text 
```
This is some
text before the merge conflicts begin.

hello world

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
test
=======
memem
>>>>>>> refs/heads/new
=======
kjnkjn
=======
kjnkjnklll
=======
imomononin
>>>>>>> refs/heads/new
>>>>>>> refs/heads/new
oh no! you broke it!

This is some more text after the merge conflicts.
```

**Comment by PhotoNomad0** [comment]
Nuts, one more test case and one more try.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK fixed the inverted logic for multiple middle sections.  Added your new test case to the unit tests.  And added another test case where there is more than one line conflicted in the merge (along with non-conflicted lines).

**Comment by PhotoNomad0** [comment]
Merged into: Fix #1610 add filter to show only chunks with conflicts

**Pull request closed without merging**
