### PR TITLE
Fix #761: Add portrait layouts for home screen, new translation screen, and edit mode

### LINKED ISSUE #761: Fix Portrait view UI
Notes
======
some scrunching  of headers and icons in portrait orientation  on the home screen

Environment
======
Environment Key | Value
:----: | :----:
version | 3.0.0
build | 97
UDID | 694f7e286991a5ec
Android Release | 4.4.2
Android SDK | 19
Brand | samsung
Device | degaswifiue

### PR DESCRIPTION
**Pull request by jshuma**
Two known issues with this:
   1. When switching between landscape and portrait in edit mode, the seek bar is displayed as in the wrong position until the user interacts (either by scrolling the page or by interacting with the seek bar). Aside from the display, interaction appears to be working correctly (and the position is correctly reflected, including when entering and exiting the activity). I'm not sure what's causing this at the moment.
   2. Due to the way `TargetTranslationActivity.dispatchTouchEvent()` calls `ViewModeFragment.onTouchEvent()`, which calls `mGesture.onTouchEvent()` before attempting to do any other touch processing, the gesture detector grabs all swipes in the activity -- including swipes on the seek bar. Even though the seek bar correct acknowledges processing the touch event, it's possible to unexpectedly trigger a swipe by using it fast enough. Notably, this is true in both portrait and landscape, but it's a lot more discoverable in portrait mode. I wasn't able to find any easy fix or workaround for this issue, and I suspect that it might require something more advanced, like breaking the seek bar out of the fragment.

Based on the importance of these known issues, it might or might not be a good idea to pull this as-is. Feedback and suggestions are welcome.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/996)

### CODE REVIEW

**Comment by neutrinog** [comment]
@jshuma regarding the scroll bar see issue #924. If there's something better then I'd like to use it.

**Comment by neutrinog** [comment]
@jshuma I just reviewed this. It looks amazing! I think item 2 you mentioned above is minor and we can put that in an issue for fix later when we have time. Item 1 however I think should be fixed before this is merged. Also I think the seekbar should be flipped in the portrait mode. It seems inconsistent to drag down from the mode buttons when on landscape mode only to have that motion reversed (drag towards the mode buttons) when in portrait mode.

**Comment by neutrinog** [comment]
for the seekbar you might be able to easily fix the scroll position by calling `scrollToFrame` in `ViewModeFragment.onCreateView()`

**Comment by jshuma** [comment]
@neutrinog OK I added a commit to address the first known issue I mentioned above. This turned out to be a tricky one to find the root cause of. Changes in `ViewModeFragment.onCreateView()` didn't actually do anything, since the root cause of the problem seems to be how instance state is restored, and that's done after the view is created. More details are in the comment on the commit. At the moment I suspect this pull request may be ready to go.

**Comment by neutrinog** [comment]
@jshuma hey does this only work for tablets? I noticed it's not working on my phone.

**Comment by jshuma** [comment]
@neutrinog Initially I checked it in as requiring 600dp width for the portrait layout, since I assumed that smaller devices would be so cramped as to be not usable in portrait for certain tasks. If you'd like, I can take some time to make portrait layouts for smaller screens… please let me know.

**Comment by jshuma** [comment]
@neutrinog Actually... I just started it up on Nexus 4. It's not looking so great in either layout there… and it's allowing both portrait and layout. I'll investigate.

**Pull request merged**
