### PR TITLE
Fix #1126 crash in 4.1 rendering read adapter

### LINKED ISSUE #1126: Crash on Android 4.1.1 dealing with Bible translations (not OBS)
Crash Exception importing mrk-kus. Stack dump:

	12-14 12:46:13.770 2041-2044/com.translationstudio.androidapp D/dalvikvm: GC_CONCURRENT freed 368K, 23% free 7208K/9287K, paused 10ms+1ms, total 14ms
	12-14 12:46:13.770 2041-2041/com.translationstudio.androidapp E/AndroidRuntime: FATAL EXCEPTION: main
	                                                                                java.lang.IndexOutOfBoundsException
	                                                                                    at android.graphics.Paint.getTextRunAdvances(Paint.java:1731)
	                                                                                    at android.graphics.Paint.getTextRunAdvances(Paint.java:1704)
	                                                                                    at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
	                                                                                    at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
	                                                                                    at android.text.StaticLayout.generate(StaticLayout.java:281)
	                                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:140)
	                                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:80)
	                                                                                    at android.text.StaticLayout.<init>(StaticLayout.java:59)
	                                                                                    at android.widget.TextView.makeSingleLayout(TextView.java:5901)
	                                                                                    at android.widget.TextView.makeNewLayout(TextView.java:5741)
	                                                                                    at android.widget.TextView.onMeasure(TextView.java:6098)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
	                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
	                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
	                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
	                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	                                                                                    at android.support.v7.widget.CardView.onMeasure(CardView.java:196)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
	                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	                                                                                    at android.view.View.measure(View.java:15172)
	                                                                                    at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:6699)
	                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
	                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
	                                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
	                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
	                                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3011)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	                                                                                    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1638)
	                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1422)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1009)
	                                                                                    at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:719)
	                                                                                    at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:733)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	                                                                                    at android.view.View.layout(View.java:13754)
	                                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4362)
	                                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	                                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	                                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)

                                                                                	at android.vi

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1126 crash in 4.1 rendering read adapter.

This is a hack to get around bug in JellyBean in rendering multiple
verses on a long line.  This hack messes up the paragraph formatting,
but at least JellyBean becomes usable and doesn't crash.

@neutrinog - this fixes the issue in JellyBean without changing for other versions of Android.  Is this what we want to do?

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1128)

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 yes I think that is fine. 
Have you tried adding just an extra space rather than a new line?

**Comment by PhotoNomad0** [comment]
@neutrinog Will try that, but the bug seems to be related to complexity when we get up to three verses on a line and the verses are longer.

**Comment by PhotoNomad0** [comment]
@neutrinog - no, inserting a space doesn't fix it.

**Comment by neutrinog** [comment]
ok that's fine for now.

**Pull request merged**
