### PR TITLE
Fix #1477 add attribution content when printing projects

### LINKED ISSUE #1477: Add attribution content when printing projects
requirements are in https://github.com/unfoldingWord-dev/ts-requirements/issues/109

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1477 add attribution content when printing projects

Changes in this pull request:
Fixed unicode fonts for printing foreign symbols.
Extended PDF printer to convert basic html to PDF chunks and paragraphs.

@neutrinog

### CODE REVIEW

**Comment by neutrinog** [comment]
can you please update the license as indicated here https://github.com/unfoldingWord-dev/ts-requirements/issues/110

**Comment by PhotoNomad0** [comment]
@neutrinog - updated the license text.

**Comment by neutrinog** [comment]
@PhotoNomad0 the project name is displayed twice in the pdf. Once on the front page then once after the new license page.

**Comment by PhotoNomad0** [comment]
@neutrinog OK will take out, but that was the original behavior.

**Comment by PhotoNomad0** [comment]
@neutrinog - it looks like the extra book title is in either of these two methods:

        addTOC(document);
        addContent(document);

It's not obvious to me where that is being added, so I will have to dig some.

**Comment by neutrinog** [comment]
@PhotoNomad0 let's not worry about the extra title page for now. I'm going to pull this so we can have it in the release.

**Pull request merged**
