### PR TITLE
Fix 356 enable sd card write

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Have SD card import and backup working.  This is a first pass pull-request (without the UI changes).  Significant changes here to make use of the Lollipop access API.

Handles these SD card usage cases:
* Pre-kitkat - SD card folder easily read/writeable and can get path calling getExternalStoragePublicDirectory()
* kitkat - SD card folder only easily read/writeable if default write disk set to SD card? And then can get path calling getExternalStoragePublicDirectory()
* Lollipop and greater without SD card - emulated card folder easily read/writeable and can get path calling getExternalStoragePublicDirectory()
* Lollipop and greater with SD card -
  * If SD card is set as default write disk - emulated card folder easily read/writeable and can get path calling getExternalStoragePublicDirectory()
  * If SD card is not set as default write disk - to access SD card you must display the file dialog where user allows app to access the SD card. When the access is granted using the dialog a special URI is returned to the app that the app needs to use to access the SD card. To make use of this URI it must be used to create a DocumentFile instance.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1216)

### CODE REVIEW

**Comment by neutrinog** [comment]
Could you move the sd card utility methods out of the appcontext and into a new class. Perhaps `com.door43.util.SDUtils`. Then if you need the context pass it in through one of the static methods. This way we keep the app context as clean as possible and make reusing this for other projects a lot easier.

**Comment by PhotoNomad0** [comment]
@neutrinog - Good suggestion.  This was a very rough first pass.

**Comment by PhotoNomad0** [comment]
@neutrinog - I have made preliminary UI changes to file browser.  Should be closer to your suggested layout.

**Comment by PhotoNomad0** [comment]
@neutrinog - hold on with this.  I am seeing exceptions thrown by git add.

**Comment by PhotoNomad0** [comment]
@neutrinog - strange - now the backup is working fine.

**Comment by PhotoNomad0** [comment]
@neutrinog - still in process here.  Highlighting of files is not working on older Android OS.

**Comment by PhotoNomad0** [comment]
@neutrinog - have another try here.  Selection is now working on older devices.

**Comment by neutrinog** [comment]
in the `Translator` can we make `exportArchive` call `exportArchiveToStream`? that way we don't have as much duplicate code. Same for `importArchive`. 

The `ArchiveDetails` could probably be simplified if we normalized the manifests first using `ArchiveImporter`, however that would mean we'd have to open up the archives and store the updated manifest somewhere... not exactly ideal. Not sure what to do in this case, just thinking out loud.

I tried to access the sd card on Android 5.0.1, 5.1.1. I got a success message about connecting to the sd card but clicking on the sd card or the internal showed the same list of files (the internal ones).

**Comment by PhotoNomad0** [comment]
@neutrinog - Can you give me more details about the Android 5.0.1 and 5.1.1?  Are they emulated devices or real?

**Comment by neutrinog** [comment]
both are real and I just confirmed both do have sd cards in them.

**Comment by PhotoNomad0** [comment]
@neutrinog In storage settings is the default write disk set to "internal storage" or "SD card"?

**Comment by PhotoNomad0** [comment]
@neutrinog - Hmm...on the Lenovo Tab 2 I have it doesn't seem to matter the default write setting.  It does switch between internal and SD Card just fine.  I don't have any other devices that can take an SD card.  What are the devices you have?

**Comment by neutrinog** [comment]
I have the same tablet as you. The lenovo a10 is the tab 2

**Comment by neutrinog** [comment]
I changed the sd card to be the default write disk and removed and reinstalled the app. Still the same thing.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK, found the logic error in the case that it could not find any tstudio files it would fall back to internal folder.  Not a good user experience.  Have made a change to fix that.

Starting to work on your other suggestions.

**Comment by PhotoNomad0** [comment]
@neutrinog - have the suggested changes implemented.  See your point about getting manifest info through ArchiveDetails.  But it is convenient to not have to extract files from each of the tstudio files in a folder list.

**Comment by neutrinog** [comment]
working good now. I adjusted the style of the buttons a little and just added a comment in the code to maybe some day refactor the archivedetails and archiveimporter.

**Comment by PhotoNomad0** [comment]
@neutrinog - Yes I knew the UI was a rough draft, but I didn't want to do too much before we had a real design.

**Pull request merged**
