### PR TITLE
Issue1421

### LINKED ISSUE #1421: add chunks.json to index
see https://github.com/unfoldingWord-dev/ts-requirements/issues/75

### PR DESCRIPTION
**Pull request by neutrinog**
Fixes #1421 .

Changes in this pull request:
- Updated the db schema to support storing chunk markers
- Added developer tool to manually inject the chunk catalog urls (since it's not available in the api yet)
- Added support for indexing chunk catalogs.
- Added method to library for retrieving project chunk markers.

Chunk markers can be retrieved from the library like so:
```
ChunkMarker[] markers = Library.getChunkMarkers(projectSlug);
```

The `ChunkMarker` class contains public final properties `chapterSlug` and `firstVerseSlug`.

> NOTE: Once the chunks are added to the main catalog in the api we'll need to make some small changes to read it directly from the api.

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - did a merge, but I get error calling: 

mMarkers = AppContext.getLibrary().getChunkMarkers(mBookShortName); (edited)

Gives error: 04-09 20:14:34.823 4271-4271/com.translationstudio.androidapp E/SQLiteLog: (1) no such table: chunk_markers

Is there a file not checked in?

**Comment by neutrinog** [comment]
Hmmm..I'll double check..I thought I got all the migration stuff working.
Guess I missed something.

**Comment by PhotoNomad0** [comment]
@neutrinog - uninstalled app and clean install.  Still says table is missing.

**Comment by PhotoNomad0** [comment]
@neutrinog - looks like it is working now.

**Pull request merged**
