### PR TITLE
#1344 Import USFM Data - Fix for out of order or missing chapters.  Updated test cases.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#1344 Import USFM Data - Fix for out of order or missing chapters.  

Changes in this pull request:
Added chapter tracking and updated test cases.

@neutrinog - fix for QA fail.

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - sorry Joel still working on this one.  Will probably have a few more tweaks.

**Comment by neutrinog** [comment]
ah ok. By the way. I updated the methods in the TargetTranslator that lists the chapters and frames so that they are returned in order. So you're out of order issue may already be fixed.

**Comment by PhotoNomad0** [comment]
@neutrinog - this was an out of order issue in the source test.  Now the data will still all be in there, and the user can fix it manually.

**Comment by PhotoNomad0** [comment]
@neutrinog - Correction: this was an out of order issue in the source text. I punted on the chapters out of order for times sake.  Didn't have time to think through the algorithm for supporting the out of order chapters.  Instead worked on supporting missing chapters and missing chapter markers.  For now the out of order chapters throws an error.  Thinking that is an artificial error rather than a typically user issue.

**Pull request merged**
