### PR TITLE
Fix for issue #895 allow edit of drafts

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix for issue #895 allow edit of drafts

@neutrinog - have a first pass at the UI to preview draft.  If user approves overwrite, then it copies to target translated project title, resource title, chapter title, and chapter fragments.  It also resets the finished flags on the target and does a commit.  Testing limited to OBS since I couldn't find any Bible books to download when I tried to update library.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1233)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - again I wonder if we want to also add the draft as a source option.  That way the reviewer could do things such as see the translated questions and notes.  Also would be able to quickly check how much has been changed by comparing the unedited and edited drafts.

**Comment by PhotoNomad0** [comment]
@neutrinog - never mind it seems that the questions, notes, and words are English only.

**Comment by neutrinog** [comment]
a draft can never be used as a source translation.

**Comment by neutrinog** [comment]
I'm working at refining this.

**Comment by PhotoNomad0** [comment]
@neutrinog - ?  Making it pretty?

**Pull request merged**
