### PR TITLE
Fix #1269 add chapter indicator to scroll view fast recycler

### LINKED ISSUE #1269: add chapter indicator to scroll view
We already have some simple functionality for this but there is a lot of room for improvement. We could use something like this https://github.com/danoz73/RecyclerViewFastScroller or this https://github.com/AnderWeb/discreteSeekBar

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1269 add chapter indicator to scroll view fast recycler

Changes in this pull request:
Removed scroller in toolbar.
Added RecyclerViewFastScroller library - fixed bug with scroll to end.  Added support for child views that are larger than recycleview window.
Added library to software licenses.
Added fast scroller to right of recycleview.  Enabled Chapter number display for review mode, chunk mode, and read mode.

@neutrinog - please take a look.  This should be more intuitive and helpful to users.

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - it looks like the library is not under active support, so I pulled it in as a project and applied the fixes.  I have a pull request for one issue submitted.  If there is any activity on that, then maybe we can consider using the library from the repos.

**Comment by neutrinog** [comment]
@PhotoNomad0  Wow that looks neat. Is it possible to place the fancy scroll bar where we had the white one?

**Comment by PhotoNomad0** [comment]
@neutrinog - think I can.  Nuts, I blew it and wasted a lot of time moving it.  Thinking we wanted a true scrollbar.

**Comment by PhotoNomad0** [comment]
@neutrinog - unfortunately the fast recycler scroller is designed to overlay the recyclerview, and is vertical only.  With a lot of work, might be able to make work with seekbar.  So now I am looking at the discreteSeekbar since that is closer to what we want.

**Comment by PhotoNomad0** [comment]
Unfortunately the discreteSeekbar is horizontal only.  Expanding the look for options.

**Comment by PhotoNomad0** [comment]
This looks like a possibility: https://github.com/moondroid/SeekBarHint
We can just do the floating hint with the existing seekbar(s).

**Comment by PhotoNomad0** [comment]
Changed to different library.

**Pull request closed without merging**
