### PR TITLE
Fix #1260 add undo/redo to review mode

### LINKED ISSUE #1260: Add undo/redo support to review mode
It would be great for the end user to be able to restore changes that are buried in the GIT archive.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1260 add undo/redo to review mode.

@neutrinog - This adds very basic undo support to the app by pulling changes archived in git repo.  Also shows a toast popup with the archive date.  This is a little slow, but usable.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1261)

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 looks pretty good for a first pass.

Some house cleaning things:

* rather than pulling out the git object and passing it back in let the TargetTranslation handle all of that internally. The ReviewModeAdapter should ideally never directly see the git object.
* When retrieving the contents of an older commit the TargetTranslation should only need to receive the FrameTranslation and commit). All file paths should be abstracted behind the TargetTranslation.
* Things like fetching the commit list can be placed in the TargetTranslation and named to be a bit clearer such as "getFrameCommitList" again this only needs the FrameTranslation
* Let's avoid modifying objects passed by reference and use return values instead (makes the code easier to read).

It's exciting to have this feature!

**Comment by PhotoNomad0** [comment]
@neutrinog - a lot of the complication is in trying to maintain state information for the chunk.  We need this for performance reasons - regenerating the history for a chunk is very slow on many devices (such as my new Asus tablet).  Another complication is that I didn’t want to commit every undo and redo operation (and thus regenerate the history), but to wait until the user stopped at a place.  It looks like I should have created a class to keep track of the state information.

**Comment by PhotoNomad0** [comment]
another complication is that the type of the chunk is contained in a private class ListItem, which can’t be passed down directly to the targetTranslation.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK, here is a second try.  Moved the undo/redo logic and optimizations into a TargetTranslationChunkHistory class.

**Pull request merged**
