### PR TITLE
Fix 1921 false hits on search

### LINKED ISSUE #1921: False hits when searching for double quote
Double quotes are found and highlighted, but it looks like it is finding false positives in every chunk.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1921 false hits on search

Changes in this pull request:
- ReviewModeAdapter - fixed issue that some searches would match characters in markup.  First if chunk is rendered, then we search rendered text (except for target card which has two possible renderings).  Otherwise if we find a match in source text, than we render text and make sure that search text is also in rendered text.  This doesn't seem to add significant delay even when searching Psalms.  
- Fixed a logic error that sometimes search up and down buttons both disappear.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1930)

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 I'm going to wait on this until I've finished migrating the ReviewModeAdapter. I'm already halfway into it and the merge conflict would be crazy.

**Comment by neutrinog** [comment]
@PhotoNomad0 I just merged in all the changes to the review mode. Can you take a look at this again?

**Comment by PhotoNomad0** [comment]
@neutrinog - hmm...changing sources now does not trigger a new search.  Taking a look.

**Comment by PhotoNomad0** [comment]
@neutrinog - working now

**Pull request merged**
