### PR TITLE
Fix 913

### PR DESCRIPTION
**Pull request by PhotoNomad0**
fix for 913 - close keyboard when move to different frame.  

Close keyboard in TargetTranslationActivity is called on the following events; 
* scroll bar movement
* swipe up/down of activity view
* toggling of view mode

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/931)

### CODE REVIEW

**Comment by neutrinog** [comment]
could we make the keyboard closing to be less sensitive? It would be nice if the user could scroll up and down a little to view different parts of the frame (especially if it is a large one or they have a small screen).


Also I forgot to mention before there's already a method for manually closing a keyboard for example:

```
// fyi. the listener can be null.
if(getListener() != null) {
  getListener().closeKeyboard();
}
```

That method is available to all of the adapters that extend `ViewModeAdapter`. Let's use that to avoid duplicate code. Sorry for not mentioning that sooner! :P

**Comment by PhotoNomad0** [comment]
@neutrinog Sounds good to me about the sensitivity.  Looking into it.

On calling the adapter from an activity - it feels very convoluted, but will look into it.

**Comment by PhotoNomad0** [comment]
@neutrinog OK found that closeKeyboard is a ViewModeFragment method.  Looks straightforward now - just need to cast mFragment to call it.

**Comment by PhotoNomad0** [comment]
@neutrinog still exploring how to allow small motion changes.  Currently using OnScrollProgress, could use change over time as way to limit.  Maybe there is a way to see if cursor has scrolled out of view?

**Comment by neutrinog** [comment]
I wonder if you could look at when the card disappears instead? Or maybe just the edittext view. I'm %85 certain there is a way to check if a view has lost visibility.

**Comment by PhotoNomad0** [comment]
I found getWindowVisibility ().  It has a limitation in that it may return visible even though view has scrolled off screen.

I also found this which may be more useful:

		Rect scrollBounds = new Rect();
		scrollView.getHitRect(scrollBounds);
		if (imageView.getLocalVisibleRect(scrollBounds)) {
		    // imageView is within the visible window
		} else {
		    // imageView is not within the visible window
}

**Comment by neutrinog** [comment]
take a look at this thread. http://stackoverflow.com/questions/19621225/knowing-when-a-view-in-a-listview-has-gone-off-the-screen

**Comment by PhotoNomad0** [comment]
@neutrinog After looking at the stackoverflow question, It looks like the final solution actually didn't use a check to see if the view has gone off screen, but just cleared the bitmap of the recycled image so it wouldn't annoy the user with old graphics.  In short he went a different direction to solve the problem.

**Comment by PhotoNomad0** [comment]
@neutrinog - currently looking into getting the focused view on motion and determining if it is still on screen.

**Comment by neutrinog** [comment]
@PhotoNomad0 if you feel like your getting stuck on this, feel free to take a break and work on another issue. I do that all the time :)

**Comment by PhotoNomad0** [comment]
Actually I think I have it working.  Am doing some code cleanup, and then I think it will be relatively simple code.

**Comment by PhotoNomad0** [comment]
2nd attempt at fix.  Please review.

**Comment by neutrinog** [comment]
awesome! I think this will work just fine.

**Pull request merged**
