### PR TITLE
Fix #1032 add option to regenerate ssh keys on auth failure

### LINKED ISSUE #1032: if a push fails due to an authentication failure re-generate and re-register the ssh keys
We should first prompt the user if they would like to try again. If they choose to try again we should re-generate the keys and re-register with the server before performing another push. 

This is necessary because if someone discovers another users's device id they could register their own public key to gain access to the repos for that device. The original user would then lose access to their repository. Allowing users to re-register their keys (without going into the developer settings) will help translators to easily re-gain access to their repos.

This can also help resolve problems that occur with issues on the server.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1032 add option to regenerate ssh keys on auth failure

@neutrinog - I think this is ready to go.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1273)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog  -  Oops, forgot to implement the following will look at this:

Technically there is another location. when you want to browse for your backups online and you have a fresh install of the app or you had previously manually regenerated your ssh keys, the check for backups would fail. This is mostly due to the fact that I never added in the code to register the ssh key if it had not already been registered (oops!). That hasn't been an issue because most people will not be uninstalling/regenerating their ssh keys.

That's a separate issue that should probably be fixed before fixing the actual issue at hand.

**Comment by neutrinog** [comment]
@PhotoNomad0 should I wait to merge this then?

**Comment by PhotoNomad0** [comment]
Yes, sorry

**Comment by PhotoNomad0** [comment]
@neutrinog - i think this is functional.  See if you like the approach. Separated the key registration code into separate class KeyRegistration, so that it could be called from both cloud import and cloud upload.

**Comment by PhotoNomad0** [comment]
@neutrinog  - this also addresses issue #1102

**Pull request merged**
