### PR TITLE
Fix #1693 Implement menu item "download available source texts" in Update Options Menu

### LINKED ISSUE #1693: Implement menu item "download available source texts" in Update Options Menu
Implement view new and updated sources workflow.  
- Need to create a new dialog as per UI design.  Complicated UI, navigation and filtering rules.
- Need to be able to query resources by either book or language.  
- Need to add search filter on list.  What are the matching rules?  For books, presume case insensitive initial text matching.  For languages, presume case insensitive matching of language name.  _Do we search the english transliteration also?_

see #1677
and unfoldingWord-dev/ts-requirements#189

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1693 Implement menu item "download available source texts" in Update Options Menu

Changes in this pull request:
- Fixes broken check for updates in ChooseSourceTranslationAdapter.
- created DownloadSourcesDialog and DownloadSourcesAdapter
- Modified DownloadResourceContainerTask to handle more than 1 download.
- changed ChooseSourceTranslationAdapter to automatically select downloaded translation.

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - OK, made another attempt here.  Think I have things close.  Probably could polish the UI, but basic functionality is here.

**Comment by neutrinog** [comment]
when I click on the choose source translations dialog from within the project the confirm button is squished.
This is because the check for updates button is really long. Perhaps we can shorten it to just "Check for updates".

**Comment by neutrinog** [comment]
one more thing. I noticed that when you download a source text it includes the helps when it gives the number of source text downloaded. That may be confusing to users. Just a thought.

**Comment by PhotoNomad0** [comment]
@neutrinog - good point - confusing.  We are already warning about tq and tn failures.

**Comment by PhotoNomad0** [comment]
> one more thing. I noticed that when you download a source text it includes the helps when it gives the number of source text downloaded. That may be confusing to users. Just a thought.

That text was changed in a separate issue 1700 (PR 1725).

**Pull request merged**
