### PR TITLE
Fix #807 request new language

### LINKED ISSUE #807: Request New Language
For some time we have discussed what users should do when they can't find their language in tS.

The kernel of the question is, should we allow them to request a new language in tS?  More verbosely, how do we prevent unnecessary creations becuase the user couldn't find the code that already exists for their language?  How do we prevent duplicates?

Potentially, we could create some "other" languages that people could choose.

Potentially, we could create a form similar to this:
* What is the name of your language?
* What are other names for your language?
* What are the names of similar languages?
* What area is this spoken in?
* Is there a language code for your language?

Those questions would allow us to:
1. Prompt them to select from a list of potential matches, or
2. Create a new private use code that would have the answers to all those questions attached to it.  When it makes it's way up to our servers we could have a surveyor review the information and add it to tD if necessary, or categorize it under an existing language code.

This is a terribly complicated issue, not so much on the technical side as it is on the survey side.  Open to any other ideas of how we could accomplish this.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #807 request new language

@neutrinog - this is a rough draft.  Take a look to see if you like this approach.  The questions are set up in a menu dynamically created in NewLanguageActivity.createQuestions() which also divides the questions into pages.

For now I just have a crude + button on the language list to add a new language.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1353)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - making some more changes after rereading the spec.

**Comment by neutrinog** [comment]
Looks good. Here are some suggestions:

* The back arrow button does not work in the questionnaire.
* The questionnaire button should *only* be visible when they are choosing the target language.
* When a question requires a Boolean response we should display both a yes and no button so it is clear to the user which one they choose. Neither should be chosen initially.
* When they have finished their new language creation the should see a dialog that tells them a temporary language code has been created for them and show them the language code.

Here are some brief notes about the code:
* Place the sha1 code in `com.door43.util.Security` as a method named `sha1`. This is where we're storing hash algorithms and will keep things organized. You'll notice an `md5` method already exists there.

**Comment by neutrinog** [comment]
also some code style preferences...
Please **don't** place opening braces on a new line. e.g.
```
public void myfunction()
{
```

but instead on the same line
```
public void myfunction() {
```

It's easier to read the code when it's formatted consistently.

**Comment by neutrinog** [comment]
some more notes. The standard when creating a generator method is to name it something like `newInstance`.  For example in `NewLanguagePackage` the `generateNew` method would instead be named `newInstance`.

**Comment by neutrinog** [comment]
sorry for all these comments. Your inbox probably hates me right now. Could you also move the new language code activity and related fragments into their own directory named `newlanguage`? e.g. `com.door43.translationstudio.newui.newlanguage`.

**Comment by neutrinog** [comment]
the app crashes when 

1. answering questions on a page
2. rotating the device.
3. clicking next

**Comment by PhotoNomad0** [comment]
It looks like we also use create as well as newInstance.

**Comment by PhotoNomad0** [comment]
Thanks for feedback.  Working on it now.

**Comment by PhotoNomad0** [comment]
@neutrinog - do you have a UI example of this:

* When a question requires a Boolean response we should display both a yes and no button so it is clear to the user which one they choose. Neither should be chosen initially.

**Comment by neutrinog** [comment]
re: there are create methods.. yes there is some inconsistencies in some of the older code. newInstance is preferred.

For the yes/no options I'm thinking a radio button. It's familiar with most people. Example:
screenshot_032216_052433_pm

**Comment by PhotoNomad0** [comment]
@neutrinog - Think I have all the fixes made here.  Tested importing and backing up new language and it seems to be working.  Rotation and back seem to be working now.

For now I just left a todo in BackupDialog mBackupToCloudButton.setOnClickListener() to finish upload to API and a todo in NewLanguageAPI.readQuestionnaire() to switch to read questions from API.

**Comment by neutrinog** [comment]
@PhotoNomad0 I don't see a button to create a new language anymore. Also, there are some weird bugs like classes are not imported, or a local variable is accessed from within an inner class without being declared final. Make sure you've pulled in the latest code from the `develop` branch.

**Comment by PhotoNomad0** [comment]
Sorry, mistakenly pushed after a pull from develop.  There were a bunch of conflicts.  I hadn’t committed what I had manually merged yet.  Now have committed and pushed.

**Comment by PhotoNomad0** [comment]
@neutrinog - Still some work to do on it for stability.

Am looking at a bug in NewTargetTranslationActivity not properly restoring state.  in onSaveInstanceState() it saves mNewTargetTranslationId and mSelectedTargetLanguage.getId().  I was thinking of using mSelectedTargetLanguage.toJson(), but it looks like the TargetLanguage.generate() is expecting different keys and the toJson() doesn't save the region.  Seems like the toJson() and generate() should be compatible.

**Comment by neutrinog** [comment]
@PhotoNomad0 when they finish the questionnaire we need to display a confirmation dialog that shows their temporary language code. Something like this.

```text
A temporary language code has been created for your translation.
my-language-code

[ok]
```

**Comment by neutrinog** [comment]
@PhotoNomad0 I see now that you do display a dialog indicating what their language code is. Is there a reason why we wait until they choose the project? Can we display it as soon as they are done with the questionnaire?

**Pull request closed without merging**
