### PR TITLE
Fix #873: prompt to edit in blind draft mode if chunk is marked done

### LINKED ISSUE #873: Done indicator in the blind draft mode
When a chunk is labeled as "done", that chunk becomes un-editable in the "blind draft" mode. It was requested that there be some indicator on the blind draft indicating it was "done". This would help people to figure out why they can't edit that frame.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
prompt to edit in blind draft mode if chunk is marked done - issue #873.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/993)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@neutrinog - Looks like it is working as intended now.  Had to be a little clever to make a disabled edittext clickable (thanks to stackoverflow).

**Comment by neutrinog** [comment]
@PhotoNomad0 looks great. One tiny change: could you make it clickable on any part of the card  just like when the card is not finished? e.g. you can click on the title, or edge of the card to display the notification not just directly on the edit text field.

**Comment by PhotoNomad0** [comment]
@neutrinog - looks like it is all clickable now.

**Comment by neutrinog** [comment]
now the dialog is not appearing when you first click on the edit text view. If you click on the title or card edge first, dismiss the dialog, then click on the edit text it will correctly displays the dialog, but not before.

**Comment by PhotoNomad0** [comment]
@neutrinog - I'm having trouble reproducing what you see on an emulated Google Nexus 10 -4.4.4 API 19.  What device are you using?

**Comment by neutrinog** [comment]
I have a lenovo tab 2 running android 5.0.1

**Comment by PhotoNomad0** [comment]
@neutrinog - Hmm - very close to the version on my phone.  Will do a clean and rebuild.  Then will try again.  So far I don't see the problem with a selection of genymotion emulators.

**Comment by PhotoNomad0** [comment]
@neutrinog - OK I received a Lenovo Tab 2 A (impressed with how fast that arrived).  Checked this build on the original 4.4.4 OS, and then upgraded to 5.0.1 OS, then another update (still 5.0.1).   Not seeing the problem you saw.  So it could be:
* a difference in our build setups (long shot - but tried building on both a PC and Mac)
* maybe I missed something on commit - verified by building on another PC from sources on github
* a difference in how we are testing.  Could you can run through the test again telling me the exact sequence of operations you are doing?

**Comment by PhotoNomad0** [comment]
@neutrinog - Think I have fixed problem with using swipe to switch to target card and detect if chunk is done.

**Comment by neutrinog** [comment]
@PhotoNomad0 ui-wise this is working great. However the finished state of the frame object is not being changed. You need to call `core.TargetTranslation.reopenFrame(Frame frame)` to mark the frame as incomplete.

**Comment by jag3773** [comment]
Correct.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by PhotoNomad0** [comment]
@neutrinog - thanks for the help, I was making it too complicated.  Have it flagging the frame as incomplete now.

**Comment by neutrinog** [comment]
@PhotoNomad0 this is working for frames. Can you add the same functionality for chapter titles, references and the project title? (There are similarly named methods available for reopening those).

**Comment by PhotoNomad0** [comment]
@neutrinog - Thanks, I'm learning more about the program.  Try this one more time.

**Pull request merged**
