### PR TITLE
Fixes #1344 Import USFM Data

### LINKED ISSUE #1344: Import USFM Data
See https://github.com/unfoldingWord-dev/ts-requirements/issues/42

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fixes #1344 Import USFM Data

Change so that user cannot continue import if processing file failed.

Added more unit test cases with missing verses.

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 

ok I realized the problem with Psalm was not that it had not verse markers (though this was a good thing to account for) but that the files are being saved with the wrong name so the app is not picking them up.

For example chapter one is saved in `001` instead of `01`. Please make sure you are using the correct chapter and frame slugs to name files and do not add extra padding. If you are able, the source text has the correct id's (that would be the most reliable) or if that is not convenient I think a good rule of thumb will be assuming two digits for everything e.g. `01` ... `99` and anything that is greater than two digets will not be padded at all e.g. `100`...`234`.

If you decide to refer to the source then there's a method `AppContext.getLibrary().getDefaultSourceTranslation()` that will return the first source translation given a project slug and source language slug.

**Comment by PhotoNomad0** [comment]
@neutrinog - please send me that file?  It would make for a great test case.

**Comment by PhotoNomad0** [comment]
@neutrinog - Nevermind, the psalms usfm file I have has the same behavior.  Only chapters 100 and above are readable after import.

**Comment by PhotoNomad0** [comment]
@neutrinog - it looks like I was using the formatting from mLibrary.getChunkMarkers.  It has for Psalms in the first entry:

chapterSlug ="001"

**Comment by PhotoNomad0** [comment]
@neutrinog - OK, it looks like Psalm import is working now.  All frames are there including the last.  Ready for review.

**Pull request merged**
