### PR TITLE
Fix QA issues #1563 app displays source translations before they are downloaded

### LINKED ISSUE #1563: App displays source translations before they are downloaded
The app is including source translations that have not yet been downloaded in the list of available source translations for a translation. If a user chooses one of these source translations their translation project will be blank. The app needs to only display source translations that have indeed been downloaded.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fixes QA questions in #1563 app displays source translations before they are downloaded

Changes in this pull request:
- Added support for updating languages.
- Removed check for missing sources on project on HomeActivity since they can now be individually downloaded in source language chooser.

@neutrinog

### CODE REVIEW

**Comment by neutrinog** [comment]
@PhotoNomad0 are you adding support for updates under this issue or in a new issue?

**Comment by neutrinog** [comment]
@PhotoNomad0 I was able to successfully update the ulb while it was already selected as a source translation.
Then I tried to update the udb (it was listed under "Available") a dialog flashed real quick but it still showed as having an update. I clicked on it again to update it and then it got stuck on the "Downloading languages" dialog.

**Comment by neutrinog** [comment]
After restarting the app, it now shows that udb is up to date. This leads me to believe there are two issues.

1. the download dialog should be dismissed if the language is already up to date.
2. the update status of a translation needs to be updated in the dialog after a download has occurred. This seems to work in the "selected" section but not "Available".

**Comment by PhotoNomad0** [comment]
@neutrinog - will check.  There should be a confirmation prompt before updating.  Not sure why it didn't stay up.

**Comment by neutrinog** [comment]
I honestly don't remember if one came up and I clicked ok. But at the very least one of the dialogs flashed. Probably the download one.

**Comment by PhotoNomad0** [comment]
@neutrinog - Ready again for review.  Fixed an interesting bug that is unique to English.  Since we have both ULB and UDB, if you select either then both are downloaded by DownloadSourceLanguageTask.  I will change onTaskFinished() to check all source languages for changes.

**Pull request merged**
